### ISSUE TITLE
reactor-netty profile start fail

### ISSUE THREAD

**Issue by yburkouski** [bclozel/spring-boot-web-reactive#11]
I 've chosed 'reactor-netty' profile ('repositories' is activated by default) and have failed server start.
 ```
 .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::  (v1.4.0.BUILD-SNAPSHOT)

2016-08-03 00:35:38.891  INFO 8188 --- [           main] s.w.reactive.ReactiveSampleApplication   : Starting ReactiveSampleApplication on yury-PC with PID 8188 (C:\Users\yury\Desktop\reactive\spring-boot-web-reactive-master\spring-boot-sample-web-reactive\target\classes started by yury in C:\Users\yury\Desktop\reactive\spring-boot-web-reactive-master)
2016-08-03 00:35:38.893  INFO 8188 --- [           main] s.w.reactive.ReactiveSampleApplication   : No active profile set, falling back to default profiles: default
2016-08-03 00:35:38.937  INFO 8188 --- [           main] o.s.b.c.e.ReactiveWebApplicationContext  : Refreshing org.springframework.boot.context.embedded.ReactiveWebApplicationContext@5b239d7d: startup date [Wed Aug 03 00:35:38 EET 2016]; root of context hierarchy
2016-08-03 00:35:39.688  INFO 8188 --- [           main] s.w.r.r.m.a.RequestMappingHandlerMapping : Mapped "{[/]}" onto public reactor.core.publisher.Mono<sample.web.reactive.BootStarter> sample.web.reactive.HomeController.starter()
2016-08-03 00:35:39.799  WARN 8188 --- [           main] o.s.b.c.e.ReactiveWebApplicationContext  : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.NoClassDefFoundError: io/netty/channel/ChannelHandler
2016-08-03 00:35:39.807 ERROR 8188 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.NoClassDefFoundError: io/netty/channel/ChannelHandler
	at org.springframework.boot.context.embedded.ReactiveWebApplicationContext.onRefresh(ReactiveWebApplicationContext.java:52) ~[classes/:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:535) ~[spring-context-5.0.0.M1.jar:5.0.0.M1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-1.4.0.BUILD-20160728.175440-591.jar:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369) [spring-boot-1.4.0.BUILD-20160728.175440-591.jar:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313) [spring-boot-1.4.0.BUILD-20160728.175440-591.jar:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185) [spring-boot-1.4.0.BUILD-20160728.175440-591.jar:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174) [spring-boot-1.4.0.BUILD-20160728.175440-591.jar:1.4.0.BUILD-SNAPSHOT]
	at sample.web.reactive.ReactiveSampleApplication.main(ReactiveSampleApplication.java:11) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:na]
Caused by: java.lang.NoClassDefFoundError: io/netty/channel/ChannelHandler
	at org.springframework.boot.context.embedded.ReactorEmbeddedReactiveHttpServer.afterPropertiesSet(ReactorEmbeddedReactiveHttpServer.java:36) ~[classes/:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.boot.context.embedded.ReactorEmbeddedHttpServerFactory.getReactiveHttpServer(ReactorEmbeddedHttpServerFactory.java:33) ~[classes/:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.boot.context.embedded.ReactiveWebApplicationContext.createReactiveHttpServer(ReactiveWebApplicationContext.java:74) ~[classes/:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.boot.context.embedded.ReactiveWebApplicationContext.onRefresh(ReactiveWebApplicationContext.java:49) ~[classes/:1.4.0.BUILD-SNAPSHOT]
	... 12 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.netty.channel.ChannelHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_66]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_66]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_66]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_66]
	... 16 common frames omitted
```

Looks like this is because missed dependency in 
`spring-boot-web-reactive-master\spring-boot-sample-web-reactive\pom.xml`
needs
```
				<dependency>
					<groupId>io.netty</groupId>
					<artifactId>netty-all</artifactId>
				</dependency>
```
inside `reactor-netty` profile

but **only with** `reactor-netty` profile I see strange behavior in a browser: pending request with forever open connection. So I should manually stop 'page' loading and only after that I'm getting result. This is strange and I think an issue cause Mono object has a value for a return.

**Comment by snicoll** [comment]
For some reason, we have to add the following dependency now

```
<dependency>
  <groupId>io.netty</groupId>
  <artifactId>netty-transport</artifactId>
</dependency>
```

@smaldini any reason why `reactory-netty` doesn't bring `netty-transport` anymore? Also If I add that, the server stops immediately. I remember that @bclozel told me it was a recent change in reactor and we should discuss how we could restore it. Any thoughts about that would be appreciated.

@yburkouski I am afraid that particular setup isn't working at the moment but we're looking into it. Thanks for the report!

**Comment by snicoll** [comment]
And `netty-all` is defined with test scope so that sample actually overrides dependency management from a transitive dep. I guess if we didn't do that, the transport part wouldn't be necessary.

**Comment by bclozel** [comment]
I've updated the sample app to avoid this mixup with the `netty-all` dependency.
