### ISSUE TITLE
Implement BasicErrorController support

### ISSUE THREAD

**Issue by lpborges** [bclozel/spring-boot-web-reactive#41]
When trying to handle a request body that mapping to a Kotlin class, when the mapping fail for a not null attribute, the application throws a exception and don't return any response to client.
Exception stacktrace:

```
java.lang.ClassCastException: reactor.core.publisher.FluxError cannot be cast to br.com.lpborges.position.receiver.Test
    at br.com.lpborges.position.receiver.TestController$test$1.get(App.kt) ~[main/:na]
    at kotlin.jvm.internal.MutablePropertyReference1.invoke(MutablePropertyReference1.java:41) ~[kotlin-runtime-1.0.4.jar:1.0.4]
    at br.com.lpborges.position.receiver.AppKt$sam$Function$9626fef9.apply(App.kt) ~[main/:na]
    at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:109) [reactor-core-3.0.2.RELEASE.jar:na]
    at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) [reactor-core-3.0.2.RELEASE.jar:na]
    at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:71) ~[reactor-core-3.0.2.RELEASE.jar:na]
    at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:892) ~[reactor-core-3.0.2.RELEASE.jar:na]
    at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:165) ~[reactor-core-3.0.2.RELEASE.jar:na]
    at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) [reactor-core-3.0.2.RELEASE.jar:na]
    at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:801) ~[reactor-core-3.0.2.RELEASE.jar:na]
    at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:561) ~[reactor-core-3.0.2.RELEASE.jar:na]
    at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:541) ~[reactor-core-3.0.2.RELEASE.jar:na]
    at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:534) ~[reactor-core-3.0.2.RELEASE.jar:na]
    at org.springframework.http.server.reactive.AbstractRequestBodyPublisher$State.onAllDataRead(AbstractRequestBodyPublisher.java:332) ~[spring-web-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
    at org.springframework.http.server.reactive.AbstractRequestBodyPublisher.onAllDataRead(AbstractRequestBodyPublisher.java:85) ~[spring-web-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
    at org.springframework.http.server.reactive.ServletServerHttpRequest$RequestBodyPublisher$RequestBodyReadListener.onAllDataRead(ServletServerHttpRequest.java:238) ~[spring-web-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:361) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_101]
```

Sample code to test:

``` kotlin
@SpringBootApplication
open class App {

    @Bean
    open fun objectMapperBuilder(): Jackson2ObjectMapperBuilder
            = Jackson2ObjectMapperBuilder().modulesToInstall(KotlinModule())
}

fun main(args: Array<String>) {
    SpringApplication.run(App::class.java, *args)
}

data class Test(var message: String)

@RestController("/test")
class TestController {

    @PostMapping(consumes=arrayOf(MediaType.APPLICATION_JSON_VALUE),
            produces=arrayOf(MediaType.APPLICATION_JSON_VALUE))
    fun test(@RequestBody test: Mono<Test>): Mono<String> =
            test.map(Test::message).doOnNext(::println)
}
```

Test on localhost:8080/test with Content-type: application/json.
Success body sample: `{"message": "abc" }`
Erro body sample:  `{}`

**Comment by bclozel** [comment]
Hi @lpborges 

I think you're relying on the fact that Boot automatically fetches your `Jackson2ObjectMapperBuilder` and uses it to configure HTTP message conversion.
This is not the case (yet) in this starter and I'll look into it as part of this issue.

So this means your Jackson kotlin module is not properly registered against the object mapper we're using to (de)serialize HTTP messages.

You can configure things manually for now by implementing `WebReactiveConfigurer` and overriding the `configureMessageReaders` or `extendMessageReaders`. Take a look at `WebReactiveConfigurationSupport.addDefaultHttpMessageReaders` to see how we're registering the default object mapper.

You can either set all the message readers in `configureMessageReaders` or just replace the jackson one in the list and use the following code to create your own custom instance:

````java
new Jackson2ServerHttpMessageReader(
					new  DecoderHttpMessageReader<>(new Jackson2JsonDecoder(objectMapper))));
```

Let me know if things are working properly once the object mapper has been configured for Kotlin.

Thanks!

**Comment by lpborges** [comment]
Hi @bclozel 
I don't think that the Kotlin module is the problem.
Using a debug, when I inpect the ObjectMapper at org.springframework.http.codec.json.Jackson2JsonEncoder (I put a breakpoint at decodeInternal method to debug the problem), and the module is registered, even when I don't declare my objectMapperBuilder bean. This because since this https://jira.spring.io/browse/SPR-14108, Spring auto detect the Kotlin module.
Continuing with the debug, when the com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException is catch, its return a ```Flux.error(new CodecException("Error while reading the data", ex));``` (Jackson2JsonDecoder, line 122).
Then I become completely lost on the Reactor Step, but at the end the error appears at console: ```java.lang.ClassCastException: reactor.core.publisher.FluxError cannot be cast to br.com.lpborges.test.Test``` and the the client is still waiting for the response, that never comes.
I can try to reproduce the same problem with Java instead of Kotlin, I think that this will happens the same way.

**Comment by lpborges** [comment]
I made the same test with Java and the problem is the same, the client don't receive a response when a error to map the Json Body occurs (I will edit the issue title to reflect this).
Here's the Java code:
```
@SpringBootApplication
@RestController("/test")
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE,
            produces = MediaType.APPLICATION_JSON_VALUE)
    public Mono<String> test(@RequestBody Mono<Test> test) {
        return test.map(Test::getMessage).doOnNext(System.out::println);
    }

    public static class Test {

        @JsonProperty(required = true)
        private String message;

        public String getMessage() {
            return message;
        }

        public void setMessage(String message) {
            this.message = message;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            Test test = (Test) o;
            return message.equals(test.message);
        }

        @Override
        public int hashCode() {
            return message.hashCode();
        }

        @Override
        public String toString() {
            return "Test{message='" + message + '\'' + '}';
        }
    }
}
```
Just POST a empty body ```{}``` on /test to reproduce the issue.
But with Java I got a different stack trace, got a NPE with a little more info:
```
java.lang.NullPointerException: The mapper returned a null value.
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:120) [reactor-core-3.0.2.RELEASE.jar:na]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:328) ~[reactor-core-3.0.2.RELEASE.jar:na]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:71) ~[reactor-core-3.0.2.RELEASE.jar:na]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:328) ~[reactor-core-3.0.2.RELEASE.jar:na]
	at reactor.core.publisher.FluxResume$ResumeSubscriber.onNext(FluxResume.java:74) ~[reactor-core-3.0.2.RELEASE.jar:na]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:328) ~[reactor-core-3.0.2.RELEASE.jar:na]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:892) ~[reactor-core-3.0.2.RELEASE.jar:na]
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:165) ~[reactor-core-3.0.2.RELEASE.jar:na]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:339) ~[reactor-core-3.0.2.RELEASE.jar:na]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152) [reactor-core-3.0.2.RELEASE.jar:na]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:339) ~[reactor-core-3.0.2.RELEASE.jar:na]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:801) ~[reactor-core-3.0.2.RELEASE.jar:na]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:561) ~[reactor-core-3.0.2.RELEASE.jar:na]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:541) ~[reactor-core-3.0.2.RELEASE.jar:na]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:534) ~[reactor-core-3.0.2.RELEASE.jar:na]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:339) ~[reactor-core-3.0.2.RELEASE.jar:na]
	at org.springframework.http.server.reactive.AbstractRequestBodyPublisher$State.onAllDataRead(AbstractRequestBodyPublisher.java:332) ~[spring-web-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.http.server.reactive.AbstractRequestBodyPublisher.onAllDataRead(AbstractRequestBodyPublisher.java:85) ~[spring-web-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.http.server.reactive.ServletServerHttpRequest$RequestBodyPublisher$RequestBodyReadListener.onAllDataRead(ServletServerHttpRequest.java:263) ~[spring-web-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:361) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoMapFuseable] :
	reactor.core.publisher.Mono.map(Mono.java:1795)
	br.com.lpborges.webreactive.Application.test(Application.java:28)
	org.springframework.web.reactive.result.method.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:175)
	org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invokeForRequest$0(InvocableHandlerMethod.java:95)
	reactor.core.publisher.MonoThenApply$MonoThenApplyManager.onNext(MonoThenApply.java:97)
	reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:892)
	reactor.core.publisher.MonoWhen$MonoWhenCoordinator.signal(MonoWhen.java:202)
	reactor.core.publisher.MonoWhen$MonoWhenSubscriber.onNext(MonoWhen.java:246)
	reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:164)
	reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:164)
	reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:89)
	reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1508)
	reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.request(FluxDefaultIfEmpty.java:65)
	reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:115)
	reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:115)
	reactor.core.publisher.MonoWhen$MonoWhenSubscriber.onSubscribe(MonoWhen.java:236)
	reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:145)
	reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:145)
	reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onSubscribe(FluxDefaultIfEmpty.java:79)
	reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
	reactor.core.publisher.MonoDefaultIfEmpty.subscribe(MonoDefaultIfEmpty.java:37)
	reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:80)
	reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:80)
	reactor.core.publisher.MonoWhen$MonoWhenCoordinator.subscribe(MonoWhen.java:126)
	reactor.core.publisher.MonoWhen.subscribe(MonoWhen.java:92)
	reactor.core.publisher.MonoThenApply.subscribe(MonoThenApply.java:57)
	reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:66)
	reactor.core.publisher.MonoOtherwise.subscribe(MonoOtherwise.java:47)
	reactor.core.publisher.MonoThenApply$MonoThenApplyManager.onNext(MonoThenApply.java:131)
	reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:71)
	reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:81)
	reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:261)
	reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:743)
	reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:126)
	reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1508)
	reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:182)
	reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1225)
	reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1188)
	reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
	reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
	reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:66)
	reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:400)
	reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:192)
	reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:95)
	reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:59)
	reactor.core.publisher.FluxConcatMap.subscribe(FluxConcatMap.java:116)
	reactor.core.publisher.MonoNext.subscribe(MonoNext.java:44)
	reactor.core.publisher.MonoOtherwiseIfEmpty.subscribe(MonoOtherwiseIfEmpty.java:47)
	reactor.core.publisher.MonoThenApply.subscribe(MonoThenApply.java:57)
	reactor.core.publisher.MonoThenApply.subscribe(MonoThenApply.java:57)
	reactor.core.publisher.MonoOtherwise.subscribe(MonoOtherwise.java:47)
	reactor.core.publisher.MonoOtherwise.subscribe(MonoOtherwise.java:47)
	reactor.core.publisher.MonoOtherwise.subscribe(MonoOtherwise.java:47)
	reactor.core.publisher.MonoThenSupply$MonoConcatIgnoreManager.drain(MonoThenSupply.java:166)
	reactor.core.publisher.MonoThenSupply.subscribe(MonoThenSupply.java:54)
	org.springframework.http.server.reactive.ServletHttpHandlerAdapter.service(ServletHttpHandlerAdapter.java:104)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
Composition chain until failing Operator :
	|_	Mono.map(Application.java:28)
	|_	Mono.doOnNext(Application.java:29)
	|_	Mono.doOnError(Application.java:30)
	|_	Flux.from(Jackson2JsonEncoder.java:89)
	|_	Flux.map(Jackson2JsonEncoder.java:89)
	|_	Mono.otherwise(DispatcherHandler.java:143)
```

**Comment by lpborges** [comment]
Testing with Java I got the same problem, the application don't return any response to client whenever a error happens with the reactive flow. Using Bean Validations is even worse, since I got no stack trace and the log just indicate that the Flux complete. Should I need to configure a doOnError on the Flux/Mono to handle the response manually?
Here is the code that I use to test:
```
@SpringBootApplication
@RestController("/test")
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE,
            produces = MediaType.APPLICATION_JSON_VALUE)
    public Mono<String> test(@Validated @RequestBody Mono<Test> test) {
        return test.map(t -> t.getMessage() == null ? "null" : t.getMessage()).doOnNext(System.out::println);
    }

    public static class Test {

        @NotNull
        @Size(max = 5)
        @JsonProperty(required = true)
        private String message;

        public String getMessage() {
            return message;
        }

        public void setMessage(String message) {
            this.message = message;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            Test test = (Test) o;
            return Objects.equals(message, test.message);
        }

        @Override
        public int hashCode() {
            return Objects.hash(message);
        }

        @Override
        public String toString() {
            return "Test{message='" + message + '\'' + '}';
        }
    }
}
```
Just post a empty body ```{}``` on /test to reproduce the issue.
Here what just appears on console:
```
2016-10-24 09:49:21.897  INFO 14608 --- [nio-8888-exec-2] reactor.unresolved                       : | onSubscribe(reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber@551dde5c)
2016-10-24 09:49:21.897  INFO 14608 --- [nio-8888-exec-2] reactor.unresolved                       : | request(unbounded)
2016-10-24 09:49:21.897  INFO 14608 --- [nio-8888-exec-2] reactor.unresolved                       : | onNext({ operator : "OnAssembly" })
2016-10-24 09:49:21.910  INFO 14608 --- [nio-8888-exec-2] reactor.unresolved                       : | onComplete()
```
I will edit the issue title to reflect this.

**Comment by lpborges** [comment]
Just did some more test. Found that the only way I receive a response is when I declare the doOnError on my flow. That is not very practical, maybe Spring could handle the error on Reactor more elegantly.
Heres the Sample controller that force a throw on reactor map, than catch the error and use the HttpServletResponse to set the response:
```
    @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE,
            produces = MediaType.APPLICATION_JSON_VALUE)
    public Mono<String> test(@Validated @RequestBody Mono<String> test, HttpServletResponse response) {
        return test.map(t -> {
                    if(true) throw new RuntimeException("Test Error on Map Mono");
                    return t;
                })
                .doOnNext(System.out::println)
                .doOnError(e -> {
                    e.printStackTrace();
                    response.setStatus(500);
                });
    }
```
If I don't declare the doOnError, the error is not handle and no response is sent back to the client.

**Comment by lpborges** [comment]
Finally I was able to handle the error.
I have to add a Error handler:
```
    @ExceptionHandler(ServerWebInputException.class)
    @ResponseStatus(HttpStatus.BAD_REQUEST)
    public String badRequestHandler() throws IOException {
        return "Invalid request body.";
    }
```
So, the real problem was that I expected that Web Reactive can handle the exception the same way the regular Spring Web using the BasicErrorController and returning a ErrorAttributes object.
Then a implementation like BasicErrorController for Reactive Controllers should resolve the issue.

**Comment by bclozel** [comment]
See spring-projects/spring-boot#8625
