### ISSUE TITLE
rxjava-reactive-streams dependency apparently needed for RxNetty

### ISSUE THREAD

**Issue by danielfernandez** [bclozel/spring-boot-web-reactive#48]
When configuring a Spring Boot app to use RxNetty, following the examples in this repository the dependencies to be added still seem to be:

```
    <dependency>
      <groupId>io.reactivex</groupId>
      <artifactId>rxnetty-common</artifactId>
    </dependency>
    <dependency>
      <groupId>io.reactivex</groupId>
      <artifactId>rxnetty-http</artifactId>
    </dependency>
```

...like they were a bit ago. However, now if only these are included we get a `ClassNotFoundException` on `rx.RxReactiveStreams`:

```
java.lang.NoClassDefFoundError: rx/RxReactiveStreams
        at org.springframework.http.server.reactive.RxNettyHttpHandlerAdapter.handle(RxNettyHttpHandlerAdapter.java:74) ~[spring-web-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
        at io.reactivex.netty.protocol.http.server.HttpConnectionHandler.handleRequest(HttpConnectionHandler.java:92) [rxnetty-http-0.5.2-rc.4.jar:0.5.2-rc.4]
        at io.reactivex.netty.protocol.http.server.HttpConnectionHandler.access$200(HttpConnectionHandler.java:40) [rxnetty-http-0.5.2-rc.4.jar:0.5.2-rc.4]
        at io.reactivex.netty.protocol.http.server.HttpConnectionHandler$1$1.call(HttpConnectionHandler.java:75) [rxnetty-http-0.5.2-rc.4.jar:0.5.2-rc.4]
        at io.reactivex.netty.protocol.http.server.HttpConnectionHandler$1$1.call(HttpConnectionHandler.java:63) [rxnetty-http-0.5.2-rc.4.jar:0.5.2-rc.4]
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69) [rxjava-1.2.2.jar:1.2.2]
        at rx.internal.operators.OperatorTake$1.onNext(OperatorTake.java:76) [rxjava-1.2.2.jar:1.2.2]
```

This class `rx.RxReactiveStreams` is in the `io.reactivex:rxjava-reactive-streams` dependency, which seems to be managed by `spring-boot-dependencies-web-reactive` but not automatically included by either `rxnetty-common` or `rxnetty-http`.

So... should that be added manually besides the other two? or maybe this should be handled differently?

**Comment by sdeleuze** [comment]
Good catch, this has changed just before M3, `rxjava-reactive-streams` is now required, we are going to update the doc and `spring-boot-sample-web-reactive/pom.xml`.
