### ISSUE TITLE
Broken validator dependency when using servers other than Tomcat

### ISSUE THREAD

**Issue by danielfernandez** [bclozel/spring-boot-web-reactive#51]
It seems there have been some changes in the validation infrastructure recently that provoke an autoconfiguration issue when using Netty, RxNetty, Jetty or Undertow.

When I create a new Spring Boot 2.0 project using http://start.spring.io and configure it to use Netty by excluding the tomcat starter and adding the Netty dependency:
```xml
                <dependency>
                    <groupId>io.projectreactor.ipc</groupId>
                    <artifactId>reactor-netty</artifactId>
                </dependency>
```

...then simply trying to start it with `mvn -U clean compile spring-boot:run` results in an exception:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'methodValidationPostProcessor' defined in class path resource [org/springframework/boot/autoconfigure/validation/ValidationAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.validation.ValidationException: HV000183: Unable to load 'javax.el.ExpressionFactory'. Check that you have the EL dependencies on the classpath, or use ParameterMessageInterpolator instead
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:566)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:223)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:702)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:527)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:736)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1161)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1150)
	at com.github.danielfernandez.testspringbootreactivenettyoutput.SpringBootReactiveNettyOutputNettyApplication.main(SpringBootReactiveNettyOutputNettyApplication.java:10)
	... 6 more
Caused by: javax.validation.ValidationException: HV000183: Unable to load 'javax.el.ExpressionFactory'. Check that you have the EL dependencies on the classpath, or use ParameterMessageInterpolator instead
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.createValidator(ValidatorFactoryImpl.java:339)
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.getValidator(ValidatorFactoryImpl.java:256)
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.<init>(MethodValidationInterceptor.java:97)
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.<init>(MethodValidationInterceptor.java:89)
	at org.springframework.validation.beanvalidation.MethodValidationPostProcessor.createMethodValidationAdvice(MethodValidationPostProcessor.java:121)
	at org.springframework.validation.beanvalidation.MethodValidationPostProcessor.afterPropertiesSet(MethodValidationPostProcessor.java:109)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1654)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1591)
	... 21 more
```

It seems the validation infrastructure is unable to find a viable implementation for `javax.el.ExpressionFactory` when Netty is used. The same happens with RxNetty, Jetty and Undertow.

This works OK in Tomcat, I suppose because Tomcat already provides an implementation for this SPI.

**Comment by bclozel** [comment]
Sorry I didn't create a dedicated issue here.
I've raised an issue on Boot itself with spring-projects/spring-boot#7500.

Is it still the case with the latest snapshot? I think @snicoll latest commit should improve the situation (haven't checked that myself yet).

**Comment by danielfernandez** [comment]
Ah OK, thanks for the info. Actually it makes sense, I should have checked Spring Boot itself...

Yes, I confirm it is happening right now with the current `2.0.0.BUILD-SNAPSHOT` of `spring-boot` and `spring-boot-autoconfigure`.

This makes me ask however... am I right in thinking that, if this is solved by adding that guard condition, we would end up having to explicitly add a validator factory implementation for all servers except for Tomcat (in order to have validation)? and if so... wouldn't this be a bit of an unexpected behaviour, the fact that your choice of server affects whether you have to manually add an implementation of a validator or not?

**Comment by danielfernandez** [comment]
> Yes, I confirm it is happening right now with the current 2.0.0.BUILD-SNAPSHOT of spring-boot and spring-boot-autoconfigure.

However, I am currently **not** seeing @snicoll's code from spring-projects/spring-boot@5d876125d, maybe this has not been included in a snapshot yet. Or maybe my maven installation is not updating for some reason even with `-U`.

**Comment by snicoll** [comment]
@danielfernandez sorry about that. We're having some issues with our master build, I am looking at it now (so it makes sense the error didn't go away as my changes are not yet included in the latest snapshot).

**Comment by snicoll** [comment]
@danielfernandez the master build is green so it should be good now.

**Comment by danielfernandez** [comment]
Thanks, I can confirm my Netty-based application now starts again with no exceptions :)

**Comment by bclozel** [comment]
Cool, thanks for confirming!
